version = "1.0.0"

[[rounds]]
number = 1
time = "2024-12-12T12:09:32+08:00"
query_essence = "解决 pnpm build 时 @template/ui 包的 TypeScript 编译错误"
key_points = """
- @template/ui 包在 DTS 构建阶段报错
- 错误显示 src/components/index.ts 文件未在项目文件列表中
- 需要检查并修正 TypeScript 配置中的文件包含设置
"""
