name = "VSCode Extension Template"

version = "1.0.0"

abstract = """
一个用于快速创建和调试 VSCode 扩展的模板项目。该项目参考 YAAC 项目的最佳实践，重点解决 F5 调试配置问题，并提供完整的开发工具链支持。主要目标包括：
1. 优化项目结构和构建配置
2. 完善调试配置和启动设置
3. 提供标准化的开发工作流
4. 集成必要的开发工具和类型支持
"""

[conversations]
"001" = { slug = "debug_config_optimization", abstract = "优化 VSCode 扩展的调试配置" }
"002" = { slug = "dependency_resolution", abstract = "解决模块依赖和构建配置问题" }
"003" = { slug = "webview_uiux_enhancement", abstract = "优化 @packages/webview 的用户界面和交互体验" }
"004" = { slug = "readme_update", abstract = "更新项目文档以反映最新修改" }
"005" = { slug = "build_error_resolution", abstract = "解决 pnpm build 过程中的 TypeScript 编译错误" }
"006" = { slug = "webview_type_definition", abstract = "修复 WebviewMessage 接口类型定义问题" }
"007" = { slug = "webview_template_optimization", abstract = "大幅优化 packages/webview 的用户界面和交互体验设计" }
